M48
; DRILL file {KiCad 9.0.5} date 2025-12-04T19:26:06-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-04T19:26:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X50.165Y-24.91
T2
X17.669Y-38.6
X24.019Y-38.6
M30
